add webhook notification to workflow

diff --git a/.github/workflows/cb-service-container.yaml b/.github/workflows/cb-service-container.yaml
--- a/.github/workflows/cb-service-container.yaml
+++ b/.github/workflows/cb-service-container.yaml
@@ -9,7 +9,7 @@ jobs:
     steps:
     - name: Update repositories
       run: |
-        apt update || echo "apt-update failed" # && apt -y upgrade 
+        apt update || echo "apt-update failed" # && apt -y upgrade
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
@@ -53,6 +53,17 @@ jobs:
     - uses: actions/checkout@v2
     - name: Build with Maven
       run: mvn --batch-mode --update-snapshots -B package --file pom.xml verify
+    - name: Report Status
+      if: always()
+      uses: ravsamhq/notify-slack-action@v1
+      with:
+        status: ${{ job.status }}
+        notify_when: 'failure,warnings'
+        notification_title: 'Repo: *{repo}*'
+        message_format: '{emoji}    *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>'
+        footer: '<{run_url}|View Full Run on GitHub>'
+      env:
+        SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
     services:
       couchbase:
         image: couchbase:enterprise-7.0.0-beta
